### ISSUE TITLE
Display / Screen Brightness setting won't stick

### ISSUE THREAD

**Issue by mjsambol** [thanksmister/android-mqtt-alarm-panel#100]
**Describe the bug**
I keep trying to turn off the Screen Brightness setting (in the Display section) and it keeps coming back to enabled within a few hours. It's not immediate, and I have no idea what is causing it to switch to enabled. My only guess is that it's related to the sun and / or weather updates being pushed from Homeassistant.

**To Reproduce**
Turn off Screen Brightness setting.
wait a few hours.
Check the setting.

**Expected behavior**
The setting should remain disabled once set that way.

**Screenshots**

**Smartphone (please complete the following information):**
Kindle Fire 8

**Comment by thanksmister** [comment]
Can you check if you are publishing the MQTT sun value, this also sets the brightness level.

**Comment by mjsambol** [comment]
Yes, I am publishing the sun's position via MQTT in order to get day or night mode. I wasn't aware that this also controls brightness, I don't see that mentioned in the documentation. 
Is it possible to get the night 'skin' without also affecting the screen brightness? Currently at night it's simply way too dark to see and operate.

**Comment by thanksmister** [comment]
The screen also dims when the screen saver is show, and returns to normal if the screen saver is hidden if you have the permission for adjusting the screen brightness level.   You can revoke the screen brightness permissions in your device settings, this will prevent the app from adjusting the screen brightness.  Go to your Settings on your device, open Apps, then select the gear icon, then select  Modify system settings and select Alarm Panel.  Disable the permissions and the app can no longer adjust the brightness level of your device.    I will investigate adding additional checks so that when screen brightness is not on, the device does not adjust the screen brightness.

**Comment by mjsambol** [comment]
I'm not sure we're talking about the same thing.

The app was working as follows until recently:

During the day, background is white. During the evening, background is
dark. The brightness remains the same, but the color of the background
changes.
At all times, after 1 minute of inactivity the screen goes dark, and then
comes back to life when motion is sensed. (Controlled, I assume, by the
"Start screen saver after..." setting and Fully Kiosk's Motion Detection
functionality.

Recently - about a week ago - this changed so that at night, in addition to
having a dark background, the screen is also extremely *dim*, to the point
of being very difficult to use. This is the behavior I am trying to roll
back.

While trying to fix this I found the setting "Screen Brightness: decrease
the screen brightness when in night node." I turned this off. That setting
does not hold, it goes back to being on within minutes, presumably when
getting the sun position update from Home Assistant.

If I turn off night mode then the screen does not get dark or dim, but this
is not ideal. I'd really like to go back to having the dark but not dim
mode. Does that make sense?

**Comment by thanksmister** [comment]
You can revoke the screen brightness permissions in your device settings, this will prevent the app from adjusting the screen brightness during the day/night mode setting.  Turning off this setting does not revoke the app permissions.  So that is what you need to do if you do not want the device to dim the screen.  

The screen dims a certain percentage of the current screen brightness.  This value is set if you go into the app settings, it is at this time it reads what it considers your app default brightness.  If you want the dim to be less, adjust the device brightness level before entering the setting screen.  However, if you don't want the screen to dim, then do as I mentioned already, revoke the permissions.

I will add a later time a way to ignore screen dimming if the screen brightness setting is turned off, but this requires more work to set your device back to automatic brightness control.  When you chose to turn on screen brightness you also gave the app permission to manually set the device brightness control.  

The reason that when you turn off night/day mode the dimming stops is because there is no call being made at that time to change the screen brightness.  If you have the app permission to set the device brightness on and its night, the screen is automatically dimmed to a set percentage of the current device brightness.

**Comment by mjsambol** [comment]
Thank you for the explanation!

**Comment by thanksmister** [comment]
I am releasing a new update (v0.8.6 Build 4) which disables the manual brightness when brightness is deactivated in the settings, releasing control of the brightness back to the device.   This also checks to see if brightness permissions are enabled and deactivates manual control of brightness if they are not.   It should prevent the screen brightness from changing through MQTT if you have the brightness toggled off in the settings.

**Comment by mjsambol** [comment]
Great, that seems ideal. Your previous suggestion has been working for me,
but this seems a more straightforward approach for the end user. Thanks for
the great support!
