### ISSUE TITLE
Feature Request: make beep sound when door / window opens or closes

### ISSUE THREAD

**Issue by snjoetw** [thanksmister/android-mqtt-alarm-panel#11]
Thanks for your great work, this project is awesome!

This is not an issue but just a feature request, hope you can consider.

For most of the alarm panel, there's a built-in piezo buzzer. Whenever door or window opens or closes, it'll make a beep sound. I'm wondering if you can make the app subscribe to additional user defined MQTT topics (e.g. one topic for each door or window) and whenever the state changes, the app will make a beep sound?

**Comment by thanksmister** [comment]
There is an option to receive notifications and speak them using TTS.  For Android devices, there is no piezo buzzer, it's just the Android sound manager of the device making the sounds.   There is another feature request for adding additional MQTT topics for taking a photo.   I am considering how to add a these features.  Thanks for the request.

**Comment by dlashua** [comment]
@snjoetw You can do this pretty easily now without another "feature" to make it happen.

Set up an automation in Home Assistant, or anything else that can publish to MQTT. Look for any condition you'd like a "beep" for and, when that condition is seen, send the following MQTT message:

topic: YOUR_BASE_PATH/command
payload: {"audio":"https://www.soundjay.com/misc/censor-beep-01.mp3"}

You can, of course, pick any sound file you like. And I advise copying it some place local (if you use Home Assistant, you can copy it to your www directory and access it as http://HA_IP:8123/local/filename.mp3

For a announced message, after the beep you can do:

topic: YOUR_BASE_PATH/command
payload: {"speak":"The Garage Door is Open"}

Since @thanksmister has added the ability to control the application in this way, it makes more sense to let your automation software handle deciding when to make a sound as opposed to @thanksmister having to add in all the different checks and requirements to support all the different things someone might want to notify on. Further more, if you're using Home Assistant, even if this feature was added in android-mqtt-alarm-panel, you'd still need to get that data into MQTT so the alarm panel could see it.

**Comment by thanksmister** [comment]
Yes, with the new features added recently, this is a better option for playing whatever sound file you want over MQTT when your door sensor is triggered. Thanks @dlashua for the suggestion and instructions.  I think I will close this feature request.
