### ISSUE TITLE
Support dynamic payloads for homie 3

### ISSUE THREAD

**Issue by fshelton79** [thanksmister/android-mqtt-alarm-panel#129]
**Is your feature request related to a problem? Please describe.**
Would like to have this app be compatible with additional Smart Home platforms by using a standard MQTT protocol

**Describe the solution you'd like**
Support homie 3 topic subscriptions

**Describe alternatives you've considered**
This alarm panel provides a better UI experience vs. using commands via dashboards

**Additional context**
https://homieiot.github.io/

**Comment by thanksmister** [comment]
I am not sure this request makes much sense.  Though the alarm panel uses MQTT commands and topics with payloads that match the Home Assistant MQTT Alarm Panel, you can still use the same MQTT topics/commands/payloads with any MQTT broker.   This already makes this control panel compatible with any home automation platform that uses MQTT.   If not, then it seems to be a limiation of the MQTT implementation of the home automation platform.

**Comment by xAPPO** [comment]
Hi, I am the developer of the MQTT integration to Hubitat elevation and the OP is trying to link your app into the Hubitat Security Monitor implementation.

I am not very familiar with your app but in terms of portability I see you can configure the status and command topics so that great.  You are fixed in your usage of the payloads for both though ?

 For example Hubitat expects armAway cf your ARM_AWAY and Hubitat status is armedAway (+armingAway) vs armed_away and pending ?

Now I may add specific support for your app although I think your objective is to make this useable on many different systems. Do you think being able to 'map' your payload values within your app is useful for broader appeal or not ?   

I realise that anyone could remap such payloads using something like Node-RED or any MQTT (in-massage-out) capable logic, and whilst topic schema remain fluid in MQTT this is necessary for many devices.

Kevin

**Comment by thanksmister** [comment]
This would require the messages to be custom and currently there is no option to change them.  This becomes a feature in the backlog, but I am certainly open for pull requests.
