### ISSUE TITLE
Feature Request: Support for different pending time for different start

### ISSUE THREAD

**Issue by snjoetw** [thanksmister/android-mqtt-alarm-panel#2]
I'd like to request for a feature that allows user to define different pending time for different state.

Currently there's only 1 pending time config for all states. That means if I choose arm_home or arm_away, they all gonna use the same pending time.

My use case is that when I select arm_home, I'd like to arm the system right away (so pending time is 0) but when I arm_away, I'd like to have a pending time of 30 seconds. Also when alarm is triggered, it'll be good if we can have a different pending time as well.

Thanks!

**Comment by thanksmister** [comment]
That's part of the MQTT Manual Control Panel component in Home Assistant.  The pending time for arm_away and arm_stay are currently the same in the HASS component, which I also agree should be configurable.  However, this is a feature of Home Assistant.  This application only reflects what the HASS component itself signals through MQTT.  

Take a look at the documentation for the Home Assistant component: https://home-assistant.io/components/alarm_control_panel.manual_mqtt/.  If you want to update the HASS component you can do a PR on that code and change it or request the feature.   

However, this application can't provide that feature as its only an interface for the HASS component and must work with its behavior.

**Comment by snjoetw** [comment]
But in the app settings there's a pending time config that you can set, I thought that's a different pending time only for the UI? That's the pending time i was talking about

**Comment by snjoetw** [comment]
I'm making changes to HA manual alarm control panel to support different pending time for different state, once that's done I'll port it over to MQTT alarm control panel. But I don't think this app is getting the pending time from HA right?

**Comment by thanksmister** [comment]
Sorry for the confusion, but those times must be set to the same as those used the Home Assistant component to work properly.  The application initially is set to the component defaults because it can't read those from MQTT, I only get the states from Home Assistant, but pending times or trigger time are not sent from Home Assistant.  So for this there is a bit of manually setting those to be the same.  Hope that makes sense. 

> pending_time (Optional): The time in seconds of the pending time before arming the alarm. Default is 60 seconds.

In the application the pending_time is being used before arming the alarm fully as shown in the small countdown timer on the red or yellow round buttons for arm home, arm away.  This is how much time you have before the alarm mode is set.  It's also used to show the enter the code dialog if the alarm is going from arm away or arm home to triggered because of some sensor being triggered for example. The pending time is still pending_time within Home Assistant. 

> trigger_time (Optional): The time in seconds of the trigger time in which the alarm is firing. Default is 120 seconds.

In the application the trigger_time is really being used because the application triggered state is set from Home Assistant.   

If you change the Home Assistant manual alarm control panel then you need to also update the application settings to reflect the same.  There are only two supported times, pending_time and trigger_time to change.   

Does all that make sense ?

If you get a chance to port over your MQTt alarm control panel changes, I will update the application to reflect those in the settings.  I have to change my code to support those changes.

**Comment by thanksmister** [comment]
If none of this makes sense, we can hash it out over Skype or Hangouts because it's probably much easier.  Let me know.

**Comment by snjoetw** [comment]
Thanks for the explanation, that all make sense. I'll keep you updated with my progress on having different pending time for different states

**Comment by snjoetw** [comment]
@thanksmister the change to support pending time per state is merged: https://github.com/home-assistant/home-assistant/pull/9358

It'll be in 0.55

**Comment by thanksmister** [comment]
Thanks @snjoetw I will update the alarm control panel once 0.55 is released.  Thanks!
