### ISSUE TITLE
Trigger Silent alarm when code is filled backwards

### ISSUE THREAD

**Issue by sgoudsme** [thanksmister/android-mqtt-alarm-panel#28]
When the secret code is filled in backwards, the system act like it is disarmed, but it sends a different payload by mqtt. Now different actions can be executed because the code was entered by force.

**Comment by thanksmister** [comment]
Interesting idea but the code isn't sent to HASS because the MQTT doesn't support sending codes.   It would have to be a separate MQTT message that is sent to HASS that would be handled in the way you want, like sending an MQTT message with "SILENT_ALARM" or "PANIC" as the payload.  I will mark this as a feature request.

**Comment by fortminor0692** [comment]
Jes. That is indeed what I meant. The system with "SILENT_ALARM" should be enough to send to HASS.

**Comment by dlashua** [comment]
A very useful feature indeed, and something present in most commercial alarm systems (often known as a duress code). Unfortunately, Home Assistant doesn't support this, natively. Luckily, it seems the manual_mqtt alarm component will ignore (with a message in the error log like this: Received unexpected payload: SILENT_ALARM 6:47 AM components/alarm_control_panel/manual_mqtt.py (WARNING)) the data it doesn't understand. So an automation could still be written to do all of the alarm type things without starting the "siren".

**Comment by dlashua** [comment]
In order for the "duress" feature to work, it can't be a special button. It has to be a separate code. The idea is... a "bad guy" is waiting in my bushes, I open my front door and he grabs me and says "disable the alarm or I kill you". So I "disable" the alarm with a different code than my real code which silently calls the police or whatever.

It has to look like I'm punching in a code. It has to do everything it would normally do to disable the alarm if I had entered the correct code. And, because Home Assistant doesn't know what a SILENT_ALARM is, it would probably have to send the DISARM payload too. But it would also need to send ... something else that Home Assistant or whatever could detect and perform whatever a "Silent Alarm" would be for their system. But as far as the alarm itself is concerned, it needs to work and look as though it has been disarmed with the correct code.
