### ISSUE TITLE
HA Dashboard

### ISSUE THREAD

**Issue by LaBoss** [thanksmister/android-mqtt-alarm-panel#3]
Hello first thanks for splendid work!

I am using the android application, and I wanted to use it in conjunction with HA DASHBOARD, ideally it would have a location in the app to put the dashboard url and a button to open a popup (like weather)

So with a tablet you can control everything! it was spectacular to have this option

Thanks

**Comment by thanksmister** [comment]
There was another user that wanted something similar.  They ended up using two applications to achieve this.  

They used 'Fully Kiosk Browser' to show their HADashbaord and another application called 'Swiftly Switch' which lets you swipe in from the edge of the screen to switch between the 'MQTT Alarm Control Panel' and 'Fully Kiosk Browser'.   

I will look into adding a separate screen to show a webpage, which could be HADashbaord or Home Assistant in kiosk mode.   For now I will close this issue since it's a feature request.

**Comment by thanksmister** [comment]
I have added an option in the settings to add your own URL for either Home Assistant or HADashboard.  Once the setting is active, you can slide the main screen to see the web page of Home Assistant.  It's available in v0.3.2.

**Comment by lundpetersen** [comment]
@thanksmister - any chance you could revisit this integration?
The current version of Home Assistant doesn't work with the build in Android browser. It just displays a blue bar and nothing else.
Would it be possible to use Chrome for rendering the webpage instead of the native browser?

**Comment by thanksmister** [comment]
The built in Android System WebView uses Chromium.  You can't just use an external browser like Chrome inside an Android application.  Sometimes Home Assistant doesn't load due to JavaScript errors.  You can try to update your Android System WebView component by searching for it on Google Play.  If your version of Android SDK is older you may not have an option to update to a version of Android System WebView that supports the a newer version of Chromium required for HA JavaScript.    Here is more information on the Android WebView https://developer.chrome.com/multidevice/webview/overview.

**Comment by lundpetersen** [comment]
I see. That makes sense.
And of course my tablet is running 4.4.4

I plan on hanging 4-5 android devices on my walls in my home using your app - and the ability to move between the alarm panel and either HADashboard or the HASS interface is perfect for me.
Would you suggest getting android tablets (running Android v. 5+) or would you use rpi3 with 7 inc touchscreen? What platform do you think will be the most stable and user friendly?

**Comment by thanksmister** [comment]
I am successfully running the Alarm panel on an old Nexus 7 from 2012 with Android 5.1.1 and Home Assistant 0.56.2. There are some slight rendering issues but it works.   I also have a RPi3 version with a 7" screen but this option can get pricey.  I think the cheapest option are probaby Amazon fire tablets as they have a fairly new OS and are also cheap.   You would then sideload the APK file from this repository onto the device.   The other option are some older phones.

**Comment by blackgearit** [comment]
Hi, have a problem with my Hass dashboard.. I've setup a password to access the front end but the internal browser of this app ask me the pass every time, even if I check 'remember me' at login screen..

**Comment by thanksmister** [comment]
Yeah, that's an issue with the internal browser used for Android and Home Assistant. It doesn't remember the login information, so if the view is reloaded, it will ask for your username/pass again.  There is no current fix at this time.   Is your device dedicated for the alarm panel?  It should work as long as you don't unload and reload the application.   I use mine as a dedicated alarm control panel, not using other applications.
