### ISSUE TITLE
publish new alarm stete is not working

### ISSUE THREAD

**Issue by animavitis** [thanksmister/android-mqtt-alarm-panel#4]
HI,

Alarm Panel is lookng great, but have problem: publishing new alarm state to MQTT is not working.
In my configuration im use MQTT ALARM PANEL, but i think it should work same way as manual alarm.

**Comment by thanksmister** [comment]
The manual alarm panel with MQTT support is the only component that will work with the application and Home Assistant.  Be sure you are using MQTT and the manual alarm panel from this Home Assistant link: https://home-assistant.io/components/alarm_control_panel.manual_mqtt/.   It will not work with a different Home Assistant component because the manual alarm panel doesn't offer MQTT support.
