### ISSUE TITLE
Provide audible timer sound

### ISSUE THREAD

**Issue by electricJP** [thanksmister/android-mqtt-alarm-panel#71]
I know it is possible to send a mp3 but a timer sound could be helpful especially while arming. It seems to me this would be very hard to implement using external MP3 sounds with "audio" command.

Check "Snapping timer loop" or "UI Element, button - timer beep" from here: https://www.soundsnap.com/tags/timer

**Comment by thanksmister** [comment]
Those are also difficult and I went that route previously.  There is already a beep sound in the application if you disable system sounds, it uses this as a default.   I opted to use the devices own alarm sound and haptic feedback instead.   But again, if you want a beep sounds file, then disable system sounds in the settings.  I will not be adding sound back to the application due to performance issues and general unreliability across multiple devices.

**Comment by electricJP** [comment]
I don't know why but I get no sound (beside haptic) whatever option I choose. I get I can try to send a TTS every 5 seconds.

**Comment by thanksmister** [comment]
When are you expecting sound?  The device alarm sound will sound when you have the alarm armed for home or away and it goes to pending mode, at which point you enter your code to disarm the system before its triggered.  Not sure how you have your system setup, but I have a 30 second delay before the alarm is triggered, and the application shows me the code dialog to disarm and its also playing the devices alarm sound.
