### ISSUE TITLE
mqtt alarm state retained

### ISSUE THREAD

**Issue by nenonano** [thanksmister/android-mqtt-alarm-panel#88]
Hi there

I'm testing your app and it's working pretty well

I found an issue: the alarm state is retained if set by your app, but it's not (retain: true is not supported anymore) in HA.

This means that if I arm the alarm from HA, your app correctly reflects alarm status, but if HA is restarted the retained value is set and it's likely to be "disarmed"

If you want to reproduce the issue:
- arm and then disarm the alarm from your app
- arm the alarm from HA web interface
- restart HA
- the alarm now is in disarmed state

IMO the state should not have the retain flag, so that the last one is the good one

HA rel. 0.87.1
your app: 0.8.5 build 7 on android lineageos 14

TIA

**Comment by thanksmister** [comment]
The retain flag is part of the MQTT     protocol it has nothing to do with HA.  HA has always had a bug that won’t remember the last MQTT state and it should.  The state of the HA alarm should be preserved through power outages not disarmed.  Also you have it backwards, the application doesn’t retain anything, it always sets its value based on the last MQTT state set.  If the application is restarted it will communicate with HA to get the last retained value from the MQTT broker.  It just picks up the last state.  If HA restarts it’s not sending out the last state of the alarm so that’s a HA bug because it should be retained.

**Comment by adipose** [comment]
I figured this was the reason you send retained messages.  HCA has an option to persist the state of the alarm, so this is not needed.  In fact, it causes other issues when HCA disarms itself (not via mqtt).

https://github.com/gazoscalvertos/Hass-Custom-Alarm/issues/81
