### ISSUE TITLE
Automatically open app when alarm triggered or pending

### ISSUE THREAD

**Issue by TheCellMC** [thanksmister/android-mqtt-alarm-panel#97]
Previously, the app used to automatically open when the alarm was triggered, however this isn't the case anymore.
I might be missing something but, when the alarm triggers or enters pending, the app doesn't open automatically.
I'm frustrated when the alarm enters pending mode when I enter the house and I have to manually open the app to then disarm the system.

**Comment by thanksmister** [comment]
I have not noticed this behavior.  Is there something else possibly going on?  Do you have to unlock your device to see the application?  The application must be running in the foreground and it must be using a screensaver in order to wake the screen on actions such as the alarm triggers.  Please provide some more information about how you are having to open the application, it sounds like the application isn't running in the foreground.

**Comment by TheCellMC** [comment]
No, my app isn’t always in foreground. As I also use my wall mounted tablet for the Hue and Ring apps I prefer to use the built in Daydream screensaver. The lock screen is completely disabled.

When the alarm triggers, the tablet automatically wakes from sleep and, for some reason, the app drawer opens. However the Alarm Panel app doesn’t open.

This used to work with a previous version of your app, however don’t spend to much time trying to fix this. I’ve got a working solution put together with tasker.

**Comment by thanksmister** [comment]
If the application is not already in the foreground, it will not open itself.  If the application isn't in the foreground, it can also be closed by the device to conserve memory.   The application is meant to run as a dedicated alarm control panel, which runs in the foreground.

**Comment by thanksmister** [comment]
Using Daydream is fine, its that the app is not running in the foreground that causes the issue.  The app may still awake the screen as this is done with a background service that runs along with the app, but nothing brings the app to the foreground.
