### ISSUE TITLE
Pass code to Yet another Alarm Panel

### ISSUE THREAD

**Issue by benmprojects** [thanksmister/android-mqtt-alarm-panel#99]
I would like your app to pas the password over mqtt to Yet another Alarm Panel

Yet another Alarm Panel supports this already.

**Comment by benmprojects** [comment]
are you still working on this project?

**Comment by thanksmister** [comment]
It’s easy to see the project commits and also the releases of you want to know the project activity.

**Comment by thanksmister** [comment]
The Alarm component from HA doesn't support receiving a code in the MQTT message, I assume this is because its not really needed.   The Alarm component of HA is an interface to the service, its not using MQTT to message.   MQTT server has authentication options, so I think they just assume that if you already have access to MQTT, additional code value is not needed.   To support codes, the MQTT component part of the Alarm panel would need to support the payload or extra parameter of the MQTT message, which it currently does not.   

I don't know how Yet another Alarm Panel works or if it receives code in its MQTT messages.     I tried to build this application to meet the requirements of MQTT components built in HA.   If you would like to contribute and make this  feature request a reality, you can do some research and determine how to best send MQTT messages to both the HA Alarm component and Yet with code support.    I know that the HA component currently doesn't support this and I am not knowledgeable about the Yet custom component.
